import { NextRequest, NextResponse } from "next/server";
import { degreesToRadians, ecfToLookAngles, eciToEcf, gstime, jday, json2satrec, propagate, shadowFraction, sunPos } from "satellite.js";
export const dynamic = "force-dynamic";
type Omm = Record<string, string | number> & { OBJECT_NAME?: string };
function direction(rad:number){const names=["Nord","Nord-Est","Est","Sud-Est","Sud","Sud-Ouest","Ouest","Nord-Ouest"];const degrees=(((rad*180/Math.PI)%360)+360)%360;return names[Math.round(degrees/45)%8];}
async function records(group:string){const r=await fetch(`https://celestrak.org/NORAD/elements/gp.php?GROUP=${group}&FORMAT=JSON`,{cache:"no-store",signal:AbortSignal.timeout(9000)});if(!r.ok)throw new Error();const j=await r.json();return Array.isArray(j)?j as Omm[]:[];}
function passesFor(omm:Omm,lat:number,lon:number,stepSeconds:number){
  const sat=json2satrec(omm as Parameters<typeof json2satrec>[0]), observer={latitude:degreesToRadians(lat),longitude:degreesToRadians(lon),height:0.2}; const result:Array<Record<string,unknown>>=[]; let current:null|{start:Date;max:Date;end:Date;maxElevation:number;direction:string;visible:boolean}=null;
  for(let seconds=0;seconds<=7*86400;seconds+=stepSeconds){const date=new Date(Date.now()+seconds*1000),pv=propagate(sat,date);if(!pv||typeof pv.position==="boolean")continue;const gmst=gstime(date),ecf=eciToEcf(pv.position,gmst),look=ecfToLookAngles(observer,ecf),elevation=look.elevation*180/Math.PI;
    if(elevation>=10){const jd=jday(date),sun=sunPos(jd),sunEcf=eciToEcf({x:sun.rsun.x*149597870.7,y:sun.rsun.y*149597870.7,z:sun.rsun.z*149597870.7},gmst),sunElevation=ecfToLookAngles(observer,sunEcf).elevation*180/Math.PI,lit=shadowFraction(sun.rsun,pv.position)<0.9,visible=sunElevation<=-6&&lit;if(!current)current={start:date,max:date,end:date,maxElevation:elevation,direction:direction(look.azimuth),visible};current.end=date;if(elevation>current.maxElevation){current.max=date;current.maxElevation=elevation;current.direction=direction(look.azimuth);}current.visible ||= visible;
    } else if(current){if(current.visible)result.push({name:omm.OBJECT_NAME??"Satellite",start:current.start.toISOString(),maximum:current.max.toISOString(),end:current.end.toISOString(),direction:current.direction,maxElevation:Math.round(current.maxElevation),durationSeconds:Math.round((current.end.getTime()-current.start.getTime())/1000)});current=null;if(result.length>=3)break;}}
  return result;
}
export async function GET(request:NextRequest){const lat=Number(request.nextUrl.searchParams.get("lat")),lon=Number(request.nextUrl.searchParams.get("lon"));if(!Number.isFinite(lat)||!Number.isFinite(lon))return NextResponse.json({iss:[],starlink:[],error:"Position requise"},{status:400});try{const [stations,starlinks]=await Promise.all([records("STATIONS"),records("STARLINK")]);const issRecord=stations.find((r)=>r.OBJECT_NAME?.toUpperCase().includes("ISS"));const iss=issRecord?passesFor(issRecord,lat,lon,30):[];const starlink=starlinks.slice(0,40).flatMap((r)=>passesFor(r,lat,lon,60).slice(0,1)).sort((a,b)=>String(a.start).localeCompare(String(b.start))).slice(0,5);return NextResponse.json({source:"CelesTrak + satellite.js SGP4",fetchedAt:new Date().toISOString(),iss,starlink,starlinkTrainConfirmed:false});}catch{return NextResponse.json({iss:[],starlink:[],error:"Calcul orbital indisponible"},{status:502});}}
